mysql:
  user: root
  password: 123456
  protocol: tcp
  address: 127.0.0.1:3306
  dbName: game
  connMaxLifeTime: 3600
  maxIdleConnNum: 1
  maxOpenConnNum: 1
redis:
  host: "localhost"
  port: 6379
  db: 0
  poolSize: 5